version: "3.4"
services:
  api:
    build: 
      context: .
      dockerfile: deploy/api/Dockerfile
    container_name: radix-api
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - radix
    depends_on:
      - mssql

  mssql:
    build: 
      context: .
      dockerfile: deploy/mssql/Dockerfile
    container_name: radix-mssql
    networks:
      - radix
    ports:
      - 1433:1433

  app:
    container_name: "radix-app"
    build: 
      context: .
      dockerfile: deploy/app/Dockerfile
    ports:
      - "80:3000"
    networks:
      - radix

networks:
  radix:
    driver: bridge